
name: Docker Build

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_overseer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2

      - name: docker hub login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }} 
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }} 
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: build image
        run: |
          docker build . -t thebungler/overseerr

      - name: docker hub push
        run: |
          docker tag overseerr thebungler/overseerr:latest
          docker tag overseerr thebungler/overseerr:1.28.0
          docker image push --all-tags thebungler/overseerr

      - name: docker hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: peterevans/dockerhub-description

